# Generated by Django 6.0.3 on 2026-04-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(choices=[('product', 'Product Enquiry'), ('booking', 'Booking Help'), ('delivery', 'Delivery & Logistics'), ('returns', 'Returns & Warranty'), ('b2b', 'Partnership / B2B'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_us',
                'ordering': ['-created_at'],
            },
        ),
    ]
