# Generated by Django 6.0.3 on 2026-04-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_remove_products_category_products_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
